<?php

declare(strict_types=1);

namespace App\Services;

use App\Models\RecurringTransaction;
use Carbon\CarbonInterface;
use Carbon\CarbonPeriod;
use Exception;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Facades\Log;

final class RecurringTransactionService
{
    public function generateFutureTransactions(RecurringTransaction $recurringTransaction, int $monthsAhead = 3): void
    {
        if (!$recurringTransaction->is_active) {
            return;
        }

        $period = $this->defineGenerationPeriod($recurringTransaction, $monthsAhead);

        collect($period)
            ->map(fn (CarbonInterface $month): CarbonInterface => $recurringTransaction->calculateExactDateForMonth($month))
            ->filter(fn (CarbonInterface $date): bool => $recurringTransaction->isValidTransactionDate($date))
            ->each(fn (CarbonInterface $date) => $this->createTransactionIfNotExists($recurringTransaction, $date));
    }

    /**
     * Drop the generated transactions from next month onward and rebuild them
     * from the (just-edited) template, so changes — including switching to or
     * from a card — propagate to the future. The current month and past stay
     * untouched.
     */
    public function regenerateFutureTransactions(RecurringTransaction $recurringTransaction, int $monthsAhead = 3): void
    {
        $nextMonth = Date::now()->startOfMonth()->addMonth();

        $recurringTransaction->transactions()
            ->where(fn (Builder $query) => $this->scopeCompetenceFrom($query, $nextMonth))
            ->delete();

        $this->generateFutureTransactions($recurringTransaction, $monthsAhead);
    }

    private function defineGenerationPeriod(RecurringTransaction $recurringTransaction, int $monthsAhead): CarbonPeriod
    {
        $startMonth = $recurringTransaction->start_date->isFuture()
            ? $recurringTransaction->start_date->copy()->startOfMonth()
            : Date::today()->startOfMonth();

        $until = $startMonth->copy()->addMonthsNoOverflow($monthsAhead);

        return CarbonPeriod::since($startMonth)
            ->until($until)
            ->{$recurringTransaction->frequency->periodUnit()}(1);
    }

    private function createTransactionIfNotExists(RecurringTransaction $recurringTransaction, CarbonInterface $transactionDate): void
    {
        $card = $recurringTransaction->creditCard;

        $exists = $recurringTransaction->transactions()
            ->where(fn (Builder $query) => $this->scopeCompetenceInMonth($query, $transactionDate))
            ->exists();

        if ($exists) {
            return;
        }

        try {
            $transaction = $recurringTransaction->transactions()->create([
                'user_id'          => $recurringTransaction->user_id,
                'category_id'      => $recurringTransaction->category_id,
                'credit_card_id'   => $recurringTransaction->credit_card_id,
                'amount'           => $recurringTransaction->amount,
                'type'             => $recurringTransaction->type,
                'description'      => $recurringTransaction->description,
                'transaction_date' => $card ? $card->effectivePaymentDate($transactionDate) : $transactionDate,
                'purchase_date'    => $card ? $transactionDate : null,
                'notes'            => 'Automatically generated by the recurring transaction',
            ]);
            $transaction->tags()->sync($recurringTransaction->tags()->pluck('tags.id')->all());
            Log::info('Recurring transaction generated successfully.', [
                'recurring_id' => $recurringTransaction->id,
                'user_id'      => $recurringTransaction->user_id,
                'date'         => $transactionDate->toDateString(),
            ]);
        } catch (Exception $exception) {
            Log::error('Failed to generate recurring transaction.', [
                'recurring_id' => $recurringTransaction->id,
                'user_id'      => $recurringTransaction->user_id,
                'date'         => $transactionDate->toDateString(),
                'error'        => $exception->getMessage(),
            ]);
        }
    }

    /**
     * Match transactions whose competence month is the given month, regardless of
     * being a card purchase (competence = purchase_date) or cash (competence =
     * transaction_date). Keeps dedup correct when a recurring switches card on/off.
     */
    private function scopeCompetenceInMonth(Builder $query, CarbonInterface $month): void
    {
        $query
            ->where(fn (Builder $cardScope) => $cardScope
                ->whereNotNull('purchase_date')
                ->whereYear('purchase_date', $month->year)
                ->whereMonth('purchase_date', $month->month))
            ->orWhere(fn (Builder $cashScope) => $cashScope
                ->whereNull('purchase_date')
                ->whereYear('transaction_date', $month->year)
                ->whereMonth('transaction_date', $month->month));
    }

    /**
     * Match transactions whose competence date is on or after the given date.
     */
    private function scopeCompetenceFrom(Builder $query, CarbonInterface $date): void
    {
        $query
            ->where(fn (Builder $cardScope) => $cardScope
                ->whereNotNull('purchase_date')
                ->where('purchase_date', '>=', $date->toDateString()))
            ->orWhere(fn (Builder $cashScope) => $cashScope
                ->whereNull('purchase_date')
                ->where('transaction_date', '>=', $date->toDateString()));
    }
}
