services:
  app:
    image: ghcr.io/combizera/preve:latest
    container_name: preve_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      CONTAINER_ROLE: app
    ports:
      - "80:8080"
    networks:
      - production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  queue:
    image: ghcr.io/combizera/preve:latest-cli
    container_name: preve_queue
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PHP_MEMORY_LIMIT=512M
    networks:
      - production
    stop_signal: SIGTERM
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: [ "sh", "./preve.sh", "queue" ]
    healthcheck:
      test: [ "CMD", "healthcheck-queue" ]
      timeout: 5s
      retries: 3
      start_period: 20s

  scheduler:
    image: ghcr.io/combizera/preve:latest-cli
    container_name: preve_scheduler
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - production
    stop_signal: SIGTERM
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: [ "sh", "./preve.sh", "scheduler" ]
    healthcheck:
      test: [ "CMD", "healthcheck-schedule" ]
      timeout: 5s
      retries: 3
      start_period: 10s

  db:
    image: postgres:15-alpine
    container_name: preve_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - production
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: preve_redis
    restart: unless-stopped
    networks:
      - production
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  production:
    driver: bridge

volumes:
  db_data:
    driver: local
